version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gamekey-postgres
    environment:
      POSTGRES_DB: gamekeymanager
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: